# Site settings
title: Legendary Tribble
description: Terrible tech advice from a burnt-out senior engineer
baseurl: "/legendary-tribble"
url: "https://felipecwb.github.io"

# Author
author:
  name: Felipe Francisco
  email: felipefrancisco.cwb@gmail.com
  github: felipecwb

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink style
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Social links
github_username: felipecwb

# Search Console verification
webmaster_verifications:
  google: x1MeS1GX6veAz5SHVVlfXPcMyL27X2t3u_0yLeYroU4
  bing: F5FC02CF87517629333FAAFFA42E27A2

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
